/* Generated by MyraPad at 8/27/2025 5:09:15 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace PlMpegNet.Samples.VideoPlayer.UI
{
	partial class MainFrame: VerticalStackPanel
	{
		private void BuildUI()
		{
			_panelVideo = new Panel();
			_panelVideo.Id = "_panelVideo";
			StackPanel.SetProportionType(_panelVideo, Myra.Graphics2D.UI.ProportionType.Fill);

			var horizontalSlider1 = new HorizontalSlider();
			horizontalSlider1.Maximum = 1;
			StackPanel.SetProportionType(horizontalSlider1, Myra.Graphics2D.UI.ProportionType.Fill);

			_labelTime = new Label();
			_labelTime.Text = "00:05/03:00";
			_labelTime.Id = "_labelTime";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(horizontalSlider1);
			horizontalStackPanel1.Widgets.Add(_labelTime);

			var label1 = new Label();
			label1.Text = "Volume";

			_sliderVolume = new HorizontalSlider();
			_sliderVolume.Maximum = 1;
			_sliderVolume.Value = 1;
			_sliderVolume.Width = 200;
			_sliderVolume.Id = "_sliderVolume";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			horizontalStackPanel2.Widgets.Add(label1);
			horizontalStackPanel2.Widgets.Add(_sliderVolume);

			
			Spacing = 4;
			Widgets.Add(_panelVideo);
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(horizontalStackPanel2);
		}

		
		public Panel _panelVideo;
		public Label _labelTime;
		public HorizontalSlider _sliderVolume;
	}
}
