// Generated by Hebron at 8/26/2025 5:51:53 PM

using System;
using System.Runtime.InteropServices;
using Hebron.Runtime;

namespace PlMpegSharp
{
	partial class PlMpeg
	{
		public enum plm_buffer_mode
		{
			PLM_BUFFER_MODE_FILE,
			PLM_BUFFER_MODE_FIXED_MEM,
			PLM_BUFFER_MODE_RING,
			PLM_BUFFER_MODE_APPEND
		}
	}
}